/* ============================================================
   MESSAGE D'INFORMATION — configuration (tout se règle ici)
   ------------------------------------------------------------
   actif      : true / false pour (dés)activer le message
   type       : "popup" (modale centrée) | "banniere" (barre haute)
   id         : identifiant. LE CHANGER réaffiche le message,
                même à ceux qui l'avaient déjà fermé.
   dateDebut  : "AAAA-MM-JJ" — affiché à partir de cette date (vide = tout de suite)
   dateFin    : "AAAA-MM-JJ" — masqué automatiquement après (vide = pas d'expiration)
   label      : petit intitulé overline
   titre      : titre du message
   texte      : corps du message (accepte du HTML simple, ex. <strong>)
   urgences   : true => affiche le bloc "urgences" dans la popup
   memoriser  : true  = ne réapparaît plus une fois fermée (normal)
                false = s'affiche à CHAQUE chargement (mode démo,
                        localStorage totalement ignoré)
   ============================================================ */
const INFO = {
  actif: true,
  type: "popup",
  id: "fermeture-aout-2026",
  dateDebut: "2026-07-15",
  dateFin: "2026-08-28",
  label: "Information",
  titre: "Fermeture annuelle",
  texte: "Le BAPU Aix-Marseille sera <strong>fermé du 3 au 28 août inclus</strong>.",
  urgences: true,
  memoriser: false   // mode démo — repasser à true avant la mise en prod réelle
};
const PAL={V:"#00AA3A",B:"#00AFF6",O:"#FF8F00",R:"#FF5243",P:"#FF8DA3"};
const PATH={ci:"M50,0A50,50 0 1 1 50,100A50,50 0 1 1 50,0Z",sT:"M0,0H100A50,50 0 0 1 0,0Z",sB:"M0,100H100A50,50 0 0 0 0,100Z",sL:"M0,0V100A50,50 0 0 0 0,0Z",sR:"M100,0V100A50,50 0 0 1 100,0Z",qTL:"M0,0L100,0A100,100 0 0 1 0,100Z",qTR:"M100,0L100,100A100,100 0 0 1 0,0Z",qBR:"M100,100L0,100A100,100 0 0 1 100,0Z",qBL:"M0,100L0,0A100,100 0 0 1 100,100Z",sq:"M0,0H100V100H0Z"};
/* TA compo extraite au pixel (6x6). Répétée pour remplir le panneau. */
const PRESET=("V.qTR V.qTL B.qBL O.qBR P.qTR P.sq O.qBR O.qBL B.sq O.sq R.qBR R.sq B.qBL R.qBR O.qBR B.qBL . V.sq B.qTL R.qTR O.sq B.sq O.qBR O.sq B.qTR B.sq V.qBL V.qBR B.sq B.sq P.qBR P.sq V.sq V.sq B.sq B.sq").trim().split(/\s+/).map(t=>t==="."?{s:"bl"}:{c:t.split(".")[0],s:t.split(".")[1]});
const NS="http://www.w3.org/2000/svg",reduce=matchMedia("(prefers-reduced-motion:reduce)").matches;
function inner(t){return t.s==="bl"?"":`<path d="${PATH[t.s]}" fill="${PAL[t.c]}"/>`}
function fill(svg,box,U,live){const r=box.getBoundingClientRect();const mob=live&&innerWidth<=820,cols=mob?Math.max(3,Math.round(r.width/r.height)):Math.max(3,Math.round(r.width/U)),rows=mob?1:Math.max(1,Math.round(r.height/U));
 svg.setAttribute("viewBox",`0 0 ${cols*100} ${rows*100}`);svg.innerHTML="";
 for(let ri=0;ri<rows;ri++)for(let ci=0;ci<cols;ci++){const t=PRESET[(ri%6)*6+(ci%6)];const g=document.createElementNS(NS,"g");g.setAttribute("class","cell");
  g.setAttribute("transform",`translate(${ci*100} ${ri*100})`);g.innerHTML=inner(t);svg.appendChild(g);
  if(reduce)g.style.opacity=1;else setTimeout(()=>g.style.opacity=1,(ci+ri)*38+30);
  if(live&&!reduce&&t.s!=="bl"&&Math.random()<0.16){g.setAttribute("class","cell breathe");const p=g.firstChild;if(p&&p.style)p.style.animationDelay=(Math.random()*6).toFixed(2)+"s";}}}
const heroSvg=document.getElementById("hero-grid"),heroBox=document.getElementById("hero-panel");
const bandSvg=document.getElementById("band1"),bandBox=bandSvg.parentElement;
function draw(){const U=innerWidth<=820?60:90;fill(heroSvg,heroBox,U,true);fill(bandSvg,bandBox,U,false)}
draw();let rt,lastW=innerWidth;addEventListener("resize",()=>{if(innerWidth===lastW)return;lastW=innerWidth;clearTimeout(rt);rt=setTimeout(draw,220)},{passive:true});
const nav=document.getElementById("nav"),os=()=>nav.classList.toggle("scrolled",scrollY>8);addEventListener("scroll",os,{passive:true});os();
(function(){if(matchMedia("(prefers-reduced-motion:reduce)").matches)return;const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("shown");io.unobserve(e.target)}}),{threshold:.12,rootMargin:"0px 0px -8% 0px"});const G=[[".qsn .amedia",0],[".qsn .acontent",0],[".pictos .overline",0],[".picto",90],[".mani .overline",0],[".mani .phrase",70],[".mani .sig",140],[".rdv-text",0],[".rdv-visual",0],[".icols>div",100],[".partners",0],[".fbot",0]];G.forEach(([sel,step])=>document.querySelectorAll(sel).forEach((el,i)=>{el.classList.add("reveal");if(step)el.style.transitionDelay=(i*step)+"ms";io.observe(el)}));})();
(function(){var reduce=matchMedia("(prefers-reduced-motion:reduce)").matches;var updP=null;if(!reduce){var P=[[".qsn .achair",0.14],[".rdv .tel-img",0.10]],els=[];P.forEach(function(pf){document.querySelectorAll(pf[0]).forEach(function(el){els.push([el,pf[1]])})});if(els.length){updP=function(){var vh=innerHeight;els.forEach(function(ef){var el=ef[0],f=ef[1];if(innerWidth<=820){el.style.removeProperty("--py");return}var r=el.getBoundingClientRect();if(r.bottom<-200||r.top>vh+200)return;var off=(r.top+r.height/2)-vh/2,py=-off*f;py=Math.max(-130,Math.min(130,py));el.style.setProperty("--py",py.toFixed(1)+"px")})};addEventListener("resize",updP,{passive:true});updP()}}var smooth=!reduce&&window.Lenis&&matchMedia("(hover:hover) and (pointer:fine)").matches;if(smooth){var lenis=new Lenis({lerp:0.1});window.__lenis=lenis;var raf=function(t){lenis.raf(t);requestAnimationFrame(raf)};requestAnimationFrame(raf);if(updP)lenis.on("scroll",updP);document.querySelectorAll('a[href^="#"]').forEach(function(a){a.addEventListener("click",function(e){var id=a.getAttribute("href");if(id&&id.length>1){var t=document.querySelector(id);if(t){e.preventDefault();lenis.scrollTo(t)}}})})}else if(updP){var tick=false;addEventListener("scroll",function(){if(!tick){tick=true;requestAnimationFrame(function(){tick=false;updP()})}},{passive:true})}})();
(function(){var rot=document.querySelector('.mani .rot');if(!rot)return;var words=["poser des mots.","être écouté·e.","se comprendre.","prendre son temps."];if(matchMedia("(prefers-reduced-motion:reduce)").matches){rot.textContent=words[0];return}var i=0;setInterval(function(){rot.classList.add("leaving");setTimeout(function(){i=(i+1)%words.length;rot.textContent=words[i];rot.classList.remove("leaving");rot.classList.add("entering");void rot.offsetWidth;rot.classList.remove("entering")},400)},3500)})();
(function(){if(matchMedia("(prefers-reduced-motion:reduce)").matches)return;var zone=null,busy=false;function gp(g){var m=/translate\(([-\d.]+)[ ,]+([-\d.]+)\)/.exec(g.getAttribute("transform")||"");return m?[+m[1]/100,+m[2]/100]:null}function build(){var svg=document.getElementById("hero-grid");if(!svg)return null;var vb=(svg.getAttribute("viewBox")||"0 0 0 0").split(/\s+/),cols=Math.round(+vb[2]/100),rows=Math.round(+vb[3]/100);if(cols<6||rows<6)return null;var c0=cols-3,r0=Math.max(0,rows-4),by={};svg.querySelectorAll("g.cell").forEach(function(g){var p=gp(g);if(p)by[Math.round(p[0])+","+Math.round(p[1])]=g});var z=[],ci,ri;for(ci=c0;ci<c0+2;ci++)for(ri=r0;ri<r0+3;ri++){var g=by[ci+","+ri];if(g&&g.querySelector("path"))z.push({g:g,ci:ci,ri:ri})}return z.length>=4?z:null}function ease(k){return 1-Math.pow(1-k,3)}function slide(g,x0,y0,x1,y1,dur,cb){var s=null;function fr(t){if(s===null)s=t;var k=Math.min(1,(t-s)/dur),e=ease(k),x=x0+(x1-x0)*e,y=y0+(y1-y0)*e;g.setAttribute("transform","translate("+(x*100)+" "+(y*100)+")");if(k<1)requestAnimationFrame(fr);else if(cb)cb()}requestAnimationFrame(fr)}function step(){if(!busy&&innerWidth>820){if(!zone||!zone[0]||!zone[0].g.isConnected)zone=build();if(zone){var pairs=[],i,j;for(i=0;i<zone.length;i++)for(j=i+1;j<zone.length;j++)if(Math.abs(zone[i].ci-zone[j].ci)+Math.abs(zone[i].ri-zone[j].ri)===1)pairs.push([i,j]);if(pairs.length){var pr=pairs[Math.floor(Math.random()*pairs.length)],a=zone[pr[0]],b=zone[pr[1]],aci=a.ci,ari=a.ri,bci=b.ci,bri=b.ri;busy=true;slide(a.g,aci,ari,bci,bri,1000,function(){busy=false});slide(b.g,bci,bri,aci,ari,1000);a.ci=bci;a.ri=bri;b.ci=aci;b.ri=ari}}}setTimeout(step,4000)}setTimeout(step,4000)})();
(function(){if(typeof INFO==="undefined"||!INFO||!INFO.actif)return;function td(){var d=new Date(),m=d.getMonth()+1,j=d.getDate();return d.getFullYear()+"-"+(m<10?"0":"")+m+"-"+(j<10?"0":"")+j}var today=td();if(INFO.dateDebut&&today<INFO.dateDebut)return;if(INFO.dateFin&&today>INFO.dateFin)return;var KEY="bapu-info-"+INFO.id;if(INFO.memoriser!==false){try{if(localStorage.getItem(KEY))return}catch(e){}}var isPop=INFO.type==="popup";var root=document.getElementById(isPop?"infoPop":"infoBan");if(!root)return;function remember(){if(INFO.memoriser===false)return;try{localStorage.setItem(KEY,"1")}catch(e){}}function lock(){var L=window.__lenis;if(L){L.stop()}else{document.documentElement.style.overflow="hidden"}}function unlock(){var L=window.__lenis;if(L){L.start()}else{document.documentElement.style.overflow=""}}var lastFocus=document.activeElement,closed=false;function foc(){return [].slice.call(root.querySelectorAll('a[href],button:not([disabled]),[tabindex]:not([tabindex="-1"])')).filter(function(el){return el.offsetWidth>0||el.offsetHeight>0})}function onKey(e){if(e.key==="Escape"){e.preventDefault();close();return}if(isPop&&e.key==="Tab"){var f=foc();if(!f.length)return;var a=f[0],b=f[f.length-1];if(e.shiftKey&&document.activeElement===a){e.preventDefault();b.focus()}else if(!e.shiftKey&&document.activeElement===b){e.preventDefault();a.focus()}}}function close(){if(closed)return;closed=true;remember();root.classList.remove("open");document.removeEventListener("keydown",onKey,true);if(isPop){unlock()}else{document.documentElement.classList.remove("has-banner")}if(lastFocus&&lastFocus.focus){try{lastFocus.focus()}catch(e){}}}root.querySelectorAll("[data-close]").forEach(function(b){b.addEventListener("click",function(e){e.preventDefault();close()})});function set(sel,val,html){var n=root.querySelector(sel);if(n){if(html)n.innerHTML=val;else n.textContent=val}}if(isPop){set("#infoLabel",INFO.label);set("#infoTitre",INFO.titre);set("#infoTexte",INFO.texte,true);var u=root.querySelector("#infoUrg");if(u&&!INFO.urgences)u.style.display="none"}else{set("#infoBanTitre",INFO.titre);set("#infoBanTexte",INFO.texte,true)}document.addEventListener("keydown",onKey,true);if(isPop)lock();requestAnimationFrame(function(){requestAnimationFrame(function(){root.classList.add("open");if(!isPop){document.documentElement.style.setProperty("--banH",root.offsetHeight+"px");document.documentElement.classList.add("has-banner")}if(isPop){var f=foc();var x=root.querySelector(".info-x");(x||f[0]||root).focus()}})})})();
