# Politique de cache BAPU
# CSS/JS : susceptibles d'évoluer -> revalidation systématique (pas de stale)
# fonts/ & img/ : assets stables -> cache long (1 an) immutable

[[headers]]
  for = "/css/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/js/main.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
